const TRIGGER_NONE = "trigger none";
const TRIGGER_START_YOUR_TURN = "start your turn";
const TRIGGER_START_OPPONENT_TURN = "start opponent turn";
const TRIGGER_START_EACH_TURN = "start each turn";
const TRIGGER_ENTER_MY_CARD = "enter my card";

const EFFECT_NONE = "effect none";
const EFFECT_ADD_FORCE = "add force";
const EFFECT_ADD_PV = "add pv";
const EFFECT_CALL_SUPPORT = "call support";

const VALUE_0 = 0;
const VALUE_1 = 1;
const VALUE_2 = 2;
const VALUE_5 = 5;

const TARGET_NONE = "target none";
const TARGET_MY_CARD = "target card";
const TARGET_MY_LEADER = "target my leader";
const TARGET_OPPONENT_LEADER = "target opponent leader";
const TARGET_MY_LEADER_NEIGHBOORS = "target my leader neighboors";
const TARGET_OPPONENT_LEADER_NEIGHBOORS = "target opponent leader neighboors";
const TARGET_MY_CARD_NEIGHBOORS = "target my card neighboors";
const TARGET_MY_EDGE_RIGHT = "target my edge right";
const TARGET_MY_EDGE_LEFT = "target my edge left";
const TARGET_OPPONENT_EDGE_RIGHT = "target opponent edge right";
const TARGET_OPPONENT_EDGE_LEFT = "target opponent edge left";
const TARGET_MY_EDGES = "target my edges";
const TARGET_OPPONENT_EDGES = "target opponent edges";
const TARGET_MY_CARDS = "target my cards";
const TARGET_OPPONENT_CARDS = "target opponent cards";
const TARGET_EVERY_CARDS = "target every cards";


const TRIGGERS_ARRAY = [
    TRIGGER_NONE,
    TRIGGER_START_YOUR_TURN,
    TRIGGER_START_OPPONENT_TURN,
    TRIGGER_START_EACH_TURN, // A TESTER
    TRIGGER_ENTER_MY_CARD,
];

const TRIGGERS_POWER_MAP = new Map();
TRIGGERS_POWER_MAP.set(TRIGGER_NONE, 0);
TRIGGERS_POWER_MAP.set(TRIGGER_START_YOUR_TURN, 2);
TRIGGERS_POWER_MAP.set(TRIGGER_START_OPPONENT_TURN, 2);
TRIGGERS_POWER_MAP.set(TRIGGER_START_EACH_TURN, 4);
TRIGGERS_POWER_MAP.set(TRIGGER_ENTER_MY_CARD, 1);

const EFFECTS_ARRAY = [
    EFFECT_NONE,
    EFFECT_ADD_FORCE,
    EFFECT_ADD_PV,
    EFFECT_CALL_SUPPORT,
];

const EFFECTS_POWER_MAP = new Map();
EFFECTS_POWER_MAP.set(EFFECT_NONE, 0);
EFFECTS_POWER_MAP.set(EFFECT_ADD_FORCE, 1);
EFFECTS_POWER_MAP.set(EFFECT_ADD_PV, 1);
EFFECTS_POWER_MAP.set(EFFECT_CALL_SUPPORT, 4);

const VALUES_ARRAY = [
    VALUE_0,
    VALUE_1,
    VALUE_2,
    VALUE_5,
];

const VALUES_POWER_MAP = new Map();
VALUES_POWER_MAP.set(VALUE_0, 0);
VALUES_POWER_MAP.set(VALUE_1, 1);
VALUES_POWER_MAP.set(VALUE_2, 2);
VALUES_POWER_MAP.set(VALUE_5, 5);

const TARGETS_ARRAY = [
    TARGET_NONE,
    TARGET_MY_CARD,
    TARGET_MY_LEADER,
    TARGET_OPPONENT_LEADER,
    TARGET_MY_LEADER_NEIGHBOORS,
    TARGET_OPPONENT_LEADER_NEIGHBOORS,
    TARGET_MY_CARD_NEIGHBOORS,
    TARGET_MY_EDGE_RIGHT,
    TARGET_MY_EDGE_LEFT,
    TARGET_OPPONENT_EDGE_RIGHT,
    TARGET_OPPONENT_EDGE_LEFT,
    TARGET_MY_EDGES,
    TARGET_OPPONENT_EDGES,
    TARGET_MY_CARDS,
    TARGET_OPPONENT_CARDS,
    TARGET_EVERY_CARDS,
];

const TARGETS_POWER_MAP = new Map();
TARGETS_POWER_MAP.set(TARGET_NONE, 0);
TARGETS_POWER_MAP.set(TARGET_MY_CARD, 1);
TARGETS_POWER_MAP.set(TARGET_MY_LEADER, 1);
TARGETS_POWER_MAP.set(TARGET_OPPONENT_LEADER, 2);
TARGETS_POWER_MAP.set(TARGET_MY_LEADER_NEIGHBOORS, 2);
TARGETS_POWER_MAP.set(TARGET_OPPONENT_LEADER_NEIGHBOORS, 2);
TARGETS_POWER_MAP.set(TARGET_MY_CARD_NEIGHBOORS, 1);
TARGETS_POWER_MAP.set(TARGET_MY_EDGE_RIGHT, 1);
TARGETS_POWER_MAP.set(TARGET_MY_EDGE_LEFT, 1);
TARGETS_POWER_MAP.set(TARGET_OPPONENT_EDGE_RIGHT, 1);
TARGETS_POWER_MAP.set(TARGET_OPPONENT_EDGE_LEFT, 1);
TARGETS_POWER_MAP.set(TARGET_MY_EDGES, 2);
TARGETS_POWER_MAP.set(TARGET_OPPONENT_EDGES, 3);
TARGETS_POWER_MAP.set(TARGET_MY_CARDS, 3);
TARGETS_POWER_MAP.set(TARGET_OPPONENT_CARDS, 3);
TARGETS_POWER_MAP.set(TARGET_EVERY_CARDS, 2);